### ISSUE TITLE
This library looks promising

### ISSUE THREAD

**Issue by ddamko** [sebestindragos/eventd#1]
I have been looking for TypeScript related DDD and EventSourcing libraries. What are your plans with this?

**Comment by sebestindragos** [comment]
I've made this library because I couldn't find any written in typescript to also fit my needs.
So far, I've used it in two production products, and it's proven to be quite ok. I was planning on adding some documentation for it, but I didn't have the time to do so.

The plan is to maintain it, and further add features as needed.
I've made some bits for working with Saga's (event sourced), but it still has some dependencies to my project's code. When i'll have some spare time, I'd like to decouple it and add that to the library also.
